from __future__ import print_function
from BinPy.Sequential import *
""" Examples for ShiftRegister class """
print ("\n---Initializing the ShiftRegister class--- ")
print ("Input is of the form (A0, A1, A2, A3, CLOCK, CIRCULAR")
print ("Initialise clock c = Clock(1, 500)\nc.start()")
c = Clock(1, 500)
c.start()
print ("fr = ShiftRegister(1, 0, 1, 1, c)    # Simple shift register")
fr = ShiftRegister(1, 0, 1, 1, c)
print ("\n---Output of the register----")
print ("fr.output()")
print (fr.output())

print (
    "fr = ShiftRegister(1, 0, 1, 1, c, cirular=1)    # Circular shift register")
fr = ShiftRegister(1, 0, 1, 1, c, 1)
print ("\n---Output of the register----")
print ("fr.output()")
print (fr.output())
print ("\n---Input changes---")
print ("fr.setInput(1, 0) #Input at index 1 is changed to 0")
fr.setInput(1, 0)
print ("\n---New Output of the register---")
print (fr.output())
print ("\n---Changing the inputs---")
print ("No need to set the number, just change the inputs")
print ("fr.setInputs(1, 1, 1, 1)")
fr.setInputs(1, 1, 1, 1)
print ("\n---To get the input states---")
print ("fr.getInputStates()")
print (fr.getInputStates())
print ("\n---New output of the register---")
print (fr.output())
print ("\n\n---Using Connectors as the input lines---")
print ("Take a Connector")
print ("conn = Connector()")
conn = Connector()
print ("\n---Set Output of gate to Connector conn---")
print ("fr.setOutput(index, conn)")
fr.setOutput(2, conn)
print ("\n---Put this connector as the input to gate1---")
print ("gate1 = AND(conn, 0)")
gate1 = AND(conn, 0)
print ("\n---Output of the gate1---")
print ("gate1.output()")
print (gate1.output())
