from __future__ import print_function
from BinPy.Combinational.combinational import *
""" Examples for BinaryAdder class """
print ("\n---Initializing the BinaryAdder class--- ")
print (
    "\n---Input is of the form ([Binary number 1],[ BInary number 2], Carry]")
print ("ba = BinaryAdder([0, 1], [1, 0], 0)")
ba = BinaryAdder([0, 1], [1, 0], 0)
print ("\n---Output of BinaryAdder")
print ("ba.output()")
print (ba.output())
print("Output is of the form [ [SUM], CARRY]")
print ("\n---Input changes---")
print ("ba.setInput(1, [0]) #Input at index 1 is changed to 0")
ba.setInput(1, [0])
print ("\n---New Output of the BinaryAdder---")
print (ba.output())
print ("\n---Changing the number of inputs---")
print ("No need to set the number, just change the inputs")
print ("Input length must be three")
print ("ba.setInputs(1, 0, 1)")
ba.setInputs([1], [0], 1)
print ("\n---To get the input states---")
print ("ba.getInputStates()")
print (ba.getInputStates())
print ("\n---New output of BinaryAdder---")
print (ba.output())
print ("\n\n---Using Connectors as the input lines---")
print ("Take a Connector")
print ("conn = Connector()")
conn = Connector()
print ("\n---Set Output of Binary Adder to Connector conn---")
print ("ba.setOutput(0, conn) # sets the conn at index 0 ")
ba.setOutput(0, conn)
print ("\n---Put this connector as the input to gate1---")
print ("gate1 = AND(conn, 0)")
gate1 = AND(conn, 0)
print ("\n---Output of the gate1---")
print ("gate1.output()")
print (gate1.output())
print ("Information about Binary Adder instance can be found by")
print ("ba")
print (ba)
