from BinPy import *
print ('Usage of AND gate')
a = Connector()
b = Connector()
AND1 = AND(1, a, 1, b)
print ('\na and b are 2 connectors')
print ('AND1 is a 4 input AND gate with inputs- 1, a, 1, b')
print ('\nSetting states to the inputs of the connector using setInputs()')
AND1.setInputs(1, '~', 1, 1)
print ('Inputs are:')
print ((AND1.getInputStates()))
print ('Output is:')
print ((AND1.output()))
print ('\nSetting state of connector b which is input to AND1 using setInput(index,state)\n')
AND1.setInput(1, 0)
print ('Inputs are:')
print ((AND1.getInputStates()))
print (('Output is:'))
print ((AND1.output()))
