from BinPy import *
print ('Usage of BUFFER gate')
print ('a and b are connectors')
print ('BUF1 is a BUFFER with inputs- a,b where a is the input and b is the enable input\n')
a = Connector()
b = Connector()
BUF1 = BUFFER(a, b)
print ('\nSetting states to the inputs of the connector using setInputs()\n')
print ('Also remember that BUFFER gate can have oly two inputs\n')
BUF1.setInputs(0, 1)
print ('Input is:')
print ((BUF1.getInputStates()))
print ('Output is:')
print ((BUF1.output()))
print ('\nSetting state of connector a which is input to BUF1 using setInput(index,state)\n')
BUF1.setInput(1, 0)
print ('Inputs are:')
print ((BUF1.getInputStates()))
print ('Output is:')
print ((BUF1.output()))
