from BinPy.Gates import *
print ('''This example is illustrate the generation of an exception while
trying to change the state of a connector which is already an ouput of some
gate''')
print ('a, b, c, d, e are connectors')
print ('a and b are inputs to NAND1 which is an 2 input NAND gate')
print ('c is the output of NAND1')
print ('c and d are inputs to XOR1 which is an 2 input XOR gate')
print ('e is the output of XOR1')
a = Connector()
b = Connector()
c = Connector()
d = Connector()
e = Connector()
NAND1 = NAND(a, b)
NAND1.setOutput(c)
print('\nSetting the states of the input connectors using NAND1.setInputs(1, 0)')
NAND1.setInputs(1, 0)
print ('Inputs are:')
print ((NAND1.getInputStates()))
print ('Output is:')
print ((NAND1.output()))
XOR1 = XOR(c, d)
XOR1.setOutput(e)
print ('\nSettin the state of connector d which is an input to XOR1 using')
print ('XOR1.setInput(1,0)')
XOR1.setInput(1, 0)
print ('Inputs are:')
print ((XOR1.getInputStates()))
print ('Output is:')
print ((XOR1.output()))
print ('\nSettin the state of connector d which is an input to XOR1 using')
print ('XOR1.setInput(0, 0)')
print ('''An exception will be generated as it is the output of NAND1
and its while thus be decided by NAND1 and cannot be changed directly''')
XOR1.setInput(0, 0)
