from __future__ import print_function
from BinPy.Gates import *
""" Examples for Connector class """
print ("\n---Initializing the Connector class--- ")
print ("conn = Connector(1)")
print("Input contains the initial value of the Connector")
conn = Connector(1)
print ("\n---State of the Connector object----")
print ("conn.state")
print (conn.state)
print ("\n---Calling the connector intance returns its state---")
print ("conn()")
print (conn())
print ("\n-- Tapping the conector---")
print ("gate = OR(0, 1)")
print ("conn.tap(gate, 'output'")
gate = OR(0, 1)
conn.tap(gate, "output")
print ("\n-- Untapping the connector---")
print ("conn.untap(gate)")
conn.untap(gate)
print ("\n-- Checking the parent of the gate---")
print ("conn.isOutputof(gate)")
conn.isOutputOf(gate)
print ("conn.isInputof(gate)")
conn.isInputOf(gate)
print ("\n---Set Output of gate to Connector conn---")
print ("gate.setOutput(conn)")
gate.setOutput(conn)
print ("\n---Put this connector as the input to gate1---")
print ("gate1 = AND(conn, 0)")
gate1 = AND(conn, 0)
print ("\n---Output of the gate1---")
print ("gate1.output()")
print (gate1.output())
print ("Information about conn instance")
print ("conn")
print (conn)
