from BinPy import *
print ('Usage of NAND gate')
print ('a and b are 2 connectors')
print ('NAND1 is a 4 input NAND gate with inputs- 1, a, 1, b')
a = Connector()
b = Connector()
NAND1 = NAND(1, a, 1, b)
print ('\nSetting states to the inputs of the connector using setInputs()')
NAND1.setInputs(1, '~', 1, 1)
print ('Inputs are:')
print ((NAND1.getInputStates()))
print ('Output is:')
print ((NAND1.output()))
print ('Setting state of connector b which is input to NAND1 using setInput(index,state)\n')
NAND1.setInput(1, 0)
print ('Inputs are:')
print ((NAND1.getInputStates()))
print (('Output is:'))
print ((NAND1.output()))
