from BinPy import *
print ('Usage of NOR gate')
print ('\na and b are 2 connectors')
print ('NOR1 is a 4 input NOR gate with inputs- 1, a, 1, b')
a = Connector()
b = Connector()
NOR1 = NOR(1, a, 1, b)
print ('\nSetting states to the inputs of the connector using setInputs()')
NOR1.setInputs(0, '~', 0, 0)
print ('Inputs are:')
print ((NOR1.getInputStates()))
print ('Output is:')
print ((NOR1.output()))
print ('\nSetting state of connector b which is input to NOR1 using setInput(index,state)\n')
NOR1.setInput(1, 1)
print ('Inputs are:')
print ((NOR1.getInputStates()))
print (('Output is:'))
print ((NOR1.output()))
