from __future__ import print_function
from BinPy.Gates import *
""" Examples for NOT class """
print ( "\n---Initializing the NOT class--- ")
print ( "gate = NOT(0)")
gate = NOT(0)
print ( "\n---Output of the NOT gate----")
print ( "gate.output()")
print ( gate.output())
print ( "\n---Input changes---")
print ( "gate.setInput(1) #Input is changed to 0")
gate.setInput(1)
print ( "\n---To get the input states---")
print ( "gate.getInputStates()")
print ( gate.getInputStates())
print ( "\n---New Output of the NOT gate---")
print ( gate.output())
print ( "\n\n---Using Connectors as the input and output lines---")
print ( "Take two Connectors")
print ( "conn1 = Connector()")
print ( "conn2 = Connector()")
conn1 = Connector()
conn2 = Connector()
print ( "\n---Initializing the NOT class--- ")
print ( "gate1 = NOT(conn1)")
gate1 = NOT(conn1)
print ( "\n---Set Output of gate to Connector conn2---")
print ( "gate1.setOutput(conn2)")
gate1.setOutput(conn2)
print ( "\n---Output of the gate1---")
print ( "gate1.output()")
print ( gate1.output())
