from BinPy import *
print ('Usage of NOT gate\n')
print ('a is a connector')
print ('NOT1 is a NOT gate with inputs- a')
a = Connector()
NOT1 = NOT(a)
print ('\nSetting states to the inputs of the connector using setInputs()')
print ('Also remember that NOT gate can have oly one input')
NOT1.setInputs(0)
print ('Input is:')
print ((NOT1.getInputStates()))
print ('Output is:')
print ((NOT1.output()))
print ('Setting state of connector a which is input to NOT1 using setInput(index,state)\n')
NOT1.setInput(0, 1)
print ('Inputs are:')
print ((NOT1.getInputStates()))
print (('Output is:'))
print ((NOT1.output()))
