from __future__ import print_function
from BinPy.Gates import *
""" Examples for OR class """
print ( "\n---Initializing the OR class--- ")
print ( "gate = OR(0, 1)")
gate = OR(0, 1)
print ( "\n---Output of the OR gate----")
print ( "gate.output()")
print ( gate.output())
print ( "\n---Input changes---")
print ( "gate.setInput(0, 1) #Input at index 0 is changed to 1")
gate.setInput(0, 1)
print ( "\n---New Output of the OR gate---")
print ( gate.output())
print ( "\n\n---Using Connectors as the input and output lines---")
print ( "conn1 = Connector()")
print ( "conn2 = Connector()")
print ( "conn3 = Connector()")
conn1 = Connector()
conn2 = Connector()
conn3 = Connector()
print ( "\n---Initializing the OR class--- ")
print ( "gate1 = OR(0, conn1, 0, conn2)")
gate1 = OR(0, conn1, 0, conn2)
print ( "\n---Set Output of gate to Connector conn3---")
print ( "gate1.setOutput(conn3)")
gate1.setOutput(conn3)
print ('''\nSetting states to the inputs of the gate
using gate1.setInputs(0, "~", 0, 0)''')
gate1.setInputs(0, '~', 0, 0)
print ('Printing Inputs of gate1 using gate1.getInputStates()')
print ((gate1.getInputStates()))
print ( "\n---Output of the gate1---")
print ( "gate1.output()")
print ( gate1.output())
print ( "\n---State of conn3---")
print ( "conn3.state")
print ( conn3.state)
