from BinPy import *
print ('Usage of OR gate\n')
print ('a and b are 2 connectors')
print ('OR1 is a 4 input OR gate with inputs- 1, a, 1, b')
a = Connector()
b = Connector()
OR1 = OR(1, a, 1, b)
print ('\nSetting states to the inputs of the connector using setInputs()')
OR1.setInputs(0, '~', 1, 0)
print ('Inputs are:')
print ((OR1.getInputStates()))
print ('Output is:')
print ((OR1.output()))
print ('\nSetting state of connector b which is input to OR1 using setInput(index,state)\n')
OR1.setInput(1, 0)
print ('Inputs are:')
print ((OR1.getInputStates()))
print (('Output is:'))
print ((OR1.output()))
