from BinPy import *
print ('Usage of XNOR gate\n')
print ('a and b are 2 connectors')
print ('XNOR1 is a 4 input XNOR gate with inputs- 1, a, 1, b')
a = Connector()
b = Connector()
XNOR1 = XNOR(1, a, 1, b)
print ('\nSetting states to the inputs of the connector using setInputs()')
XNOR1.setInputs(0, '~', 1, 0)
print ('Inputs are:')
print ((XNOR1.getInputStates()))
print ('Output is:')
print ((XNOR1.output()))
print ('\nSetting state of connector b which is input to XNOR1 using setInput(index,state)\n')
XNOR1.setInput(1, 0)
print ('Inputs are:')
print ((XNOR1.getInputStates()))
print (('Output is:'))
print ((XNOR1.output()))
