from BinPy import *
print ('Usage of XOR gate\n')
print ('a and b are 2 connectors')
print ('XOR1 is a 4 input XOR gate with inputs- 1, a, 1, b')
a = Connector()
b = Connector()
XOR1 = XOR(1, a, 1, b)
print ('\nSetting states to the inputs of the connector using setInputs()')
XOR1.setInputs(0, '~', 1, 1)
print ('Inputs are:')
print ((XOR1.getInputStates()))
print ('Output is:')
print ((XOR1.output()))
print ('\nSetting state of connector b which is input to XOR1 using setInput(index,state)\n')
XOR1.setInput(1, 0)
print ('Inputs are:')
print ((XOR1.getInputStates()))
print (('Output is:'))
print ((XOR1.output()))
